title: Thiago Prates Bossardi
logo: profile-pic (2).png
description: 
:house: London, UK		
📱07495 796 478	               
:email: thiagopbossardi@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
